version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: empleado-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: empleados_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password